apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: checkbot
  name: checkbot
spec:
  replicas: 1
  selector:
    app: checkbot
    deploymentconfig: checkbot
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: checkbot
        deploymentconfig: checkbot
    spec:
      containers:
        - args:
            - '-scriptBase=/app/scripts'
            - '-metricsPrefix=checkbot'
            - '-logLevel=info'
            - '-enableSandbox=true'
          command:
            - ./main
          image: >-
            tobiasdenzler/checkbot:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4444
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: checkbot
          ports:
            - containerPort: 4444
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4444
              scheme: HTTPS
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/scripts/operation
              name: scripts-operation
              readOnly: true
            - mountPath: /app/scripts/compliance
              name: scripts-compliance
              readOnly: true
            - mountPath: /app/certs
              name: checkbot-certs
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: checkbot
      serviceAccountName: checkbot
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 493
            name: scripts-operation
          name: scripts-operation
        - configMap:
            defaultMode: 493
            name: scripts-compliance
          name: scripts-compliance
        - name: checkbot-certs
          secret:
            defaultMode: 420
            secretName: checkbot-certs
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - checkbot
