name: checkbot
on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Set version env
      run: echo ::set-env name=APP_VERSION::$(git describe --tags)

    - name: Set build env
      run: echo ::set-env name=APP_BUILD::$(date +%FT%T%z)

    - name: Debug
      run: echo $APP_VERSION $APP_BUILD
    - name: Github
      run: echo ${{ github.ref }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Test
      run: go test -v -short -race ./...

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.11
      env:
        GIT_VERSION: ${{ env.APP_VERSION }}
        GIT_BUILD: ${{ env.APP_BUILD }}
      with:
        name: tobiasdenzler/checkbot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tag_names: true
        buildargs: GIT_VERSION,GIT_BUILD
