name: Go
on:
  push:
    branches:
    - master
    - release/*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: cedrickring/golang-action@1.4.1
      with:
        args: go test -v -short -race ./...
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: tobiasdenzler/checkbot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile